/********************************************************************
* libRHICfEvent.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libRHICfEvent.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibRHICfEvent();
extern void G__cpp_setup_inheritancelibRHICfEvent();
extern void G__cpp_setup_typetablelibRHICfEvent();
extern void G__cpp_setup_memvarlibRHICfEvent();
extern void G__cpp_setup_globallibRHICfEvent();
extern void G__cpp_setup_memfunclibRHICfEvent();
extern void G__cpp_setup_funclibRHICfEvent();
extern void G__set_cpp_environmentlibRHICfEvent();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RHICfBBC.h"
#include "RHICfZDC.h"
#include "RHICfFC.h"
#include "RHICfRoman.h"
#include "RHICfSimP.h"
#include "RHICfSimIncidents.h"
#include "ParticlesInfo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libRHICfEventLN_TClass;
extern G__linked_taginfo G__libRHICfEventLN_TBuffer;
extern G__linked_taginfo G__libRHICfEventLN_TMemberInspector;
extern G__linked_taginfo G__libRHICfEventLN_TObject;
extern G__linked_taginfo G__libRHICfEventLN_TNamed;
extern G__linked_taginfo G__libRHICfEventLN_TString;
extern G__linked_taginfo G__libRHICfEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libRHICfEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libRHICfEventLN_TObjArray;
extern G__linked_taginfo G__libRHICfEventLN_TClonesArray;
extern G__linked_taginfo G__libRHICfEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libRHICfEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libRHICfEventLN_RHICfBBC;
extern G__linked_taginfo G__libRHICfEventLN_RHICfZDC;
extern G__linked_taginfo G__libRHICfEventLN_RHICfFC;
extern G__linked_taginfo G__libRHICfEventLN_RHICfRoman;
extern G__linked_taginfo G__libRHICfEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__libRHICfEventLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__libRHICfEventLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__libRHICfEventLN_TVector3;
extern G__linked_taginfo G__libRHICfEventLN_TLorentzVector;
extern G__linked_taginfo G__libRHICfEventLN_RHICfSimP;
extern G__linked_taginfo G__libRHICfEventLN_RHICfSimIncidents;
extern G__linked_taginfo G__libRHICfEventLN_ParticlesInfo;

/* STUB derived class for protected member access */
