/********************************************************************
* libLHCfFunction.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libLHCfFunction.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibLHCfFunction();
extern void G__cpp_setup_inheritancelibLHCfFunction();
extern void G__cpp_setup_typetablelibLHCfFunction();
extern void G__cpp_setup_memvarlibLHCfFunction();
extern void G__cpp_setup_globallibLHCfFunction();
extern void G__cpp_setup_memfunclibLHCfFunction();
extern void G__cpp_setup_funclibLHCfFunction();
extern void G__set_cpp_environmentlibLHCfFunction();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "A1Cal1ToCal2.h"
#include "A1GainCalibration.h"
#include "A1PedeSubtract.h"
#include "A1RawToCal1.h"
#include "A1CrossTalk.h"
#include "A1LHCCrossTalk.h"
#include "A2Cal1ToCal2.h"
#include "A2GainCalibration.h"
#include "A2PedeSubtract.h"
#include "A2RawToCal1.h"
#include "A2RawToCal1Silicon.h"
#include "ADCRange.h"
#include "Arm2Alignment.h"
#include "ConParticleDefine.h"
#include "ConScifiPosition.h"
#include "ConShowerLeakage.h"
#include "FCGain.h"
#include "FuncForLHC.h"
#include "LHCfRunInfoTable.h"
#include "MyFunction.h"
#include "PMTGain.h"
#include "PMTSatu.h"
#include "PMTSatuCorrection.h"
#include "ParticleID01.h"
#include "ParticleID02.h"
#include "SciFiPosCalculation.h"
#include "ScifiGain.h"
#include "ScifiIncidentPosition02.h"
#include "ScifiPosTable.h"
#include "ScintiPosDependence.h"
#include "SiliconGain.h"
#include "SPSAdamoPedeSubtract.h"
#include "TransitionFit.h"
#include "RHICfRunInfoTable.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libLHCfFunctionLN_TClass;
extern G__linked_taginfo G__libLHCfFunctionLN_TBuffer;
extern G__linked_taginfo G__libLHCfFunctionLN_TDirectory;
extern G__linked_taginfo G__libLHCfFunctionLN_TMemberInspector;
extern G__linked_taginfo G__libLHCfFunctionLN_TObject;
extern G__linked_taginfo G__libLHCfFunctionLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__libLHCfFunctionLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__libLHCfFunctionLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__libLHCfFunctionLN_string;
extern G__linked_taginfo G__libLHCfFunctionLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libLHCfFunctionLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfFunctionLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libLHCfFunctionLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfFunctionLN_A1Cal1;
extern G__linked_taginfo G__libLHCfFunctionLN_A1Cal2;
extern G__linked_taginfo G__libLHCfFunctionLN_ADCRange;
extern G__linked_taginfo G__libLHCfFunctionLN_A1Cal1ToCal2;
extern G__linked_taginfo G__libLHCfFunctionLN_ConParticleDefine;
extern G__linked_taginfo G__libLHCfFunctionLN_PMTGain;
extern G__linked_taginfo G__libLHCfFunctionLN_ScifiGain;
extern G__linked_taginfo G__libLHCfFunctionLN_FCGain;
extern G__linked_taginfo G__libLHCfFunctionLN_A1GainCalibration;
extern G__linked_taginfo G__libLHCfFunctionLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__libLHCfFunctionLN_A1PedeSubtract;
extern G__linked_taginfo G__libLHCfFunctionLN_A1Raw;
extern G__linked_taginfo G__libLHCfFunctionLN_A1Raw_pp2015;
extern G__linked_taginfo G__libLHCfFunctionLN_RHICfRaw_Op2017;
extern G__linked_taginfo G__libLHCfFunctionLN_ScifiPosTable;
extern G__linked_taginfo G__libLHCfFunctionLN_A1RawToCal1;
extern G__linked_taginfo G__libLHCfFunctionLN_A1RawToCal1cLcLRAWTOCAL_FORMAT;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__libLHCfFunctionLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__libLHCfFunctionLN_A1CrossTalk;
extern G__linked_taginfo G__libLHCfFunctionLN_A1LHCCrossTalk;
extern G__linked_taginfo G__libLHCfFunctionLN_A2Cal2;
extern G__linked_taginfo G__libLHCfFunctionLN_A2Cal1;
extern G__linked_taginfo G__libLHCfFunctionLN_A2Cal1ToCal2;
extern G__linked_taginfo G__libLHCfFunctionLN_SiliconGain;
extern G__linked_taginfo G__libLHCfFunctionLN_A2GainCalibration;
extern G__linked_taginfo G__libLHCfFunctionLN_A2PedeSubtract;
extern G__linked_taginfo G__libLHCfFunctionLN_A2Raw;
extern G__linked_taginfo G__libLHCfFunctionLN_A2Raw_pPb2013;
extern G__linked_taginfo G__libLHCfFunctionLN_A2Raw_pp2015;
extern G__linked_taginfo G__libLHCfFunctionLN_A2Raw_pPb2016;
extern G__linked_taginfo G__libLHCfFunctionLN_A2RawToCal1;
extern G__linked_taginfo G__libLHCfFunctionLN_A2RawToCal1cLcLRAWTOCAL_FORMAT;
extern G__linked_taginfo G__libLHCfFunctionLN_TF1;
extern G__linked_taginfo G__libLHCfFunctionLN_TH1F;
extern G__linked_taginfo G__libLHCfFunctionLN_SILICON_RAW;
extern G__linked_taginfo G__libLHCfFunctionLN_A2RawToCal1Silicon;
extern G__linked_taginfo G__libLHCfFunctionLN_Arm2Hit;
extern G__linked_taginfo G__libLHCfFunctionLN_Arm2Alignment;
extern G__linked_taginfo G__libLHCfFunctionLN_MyFilePath;
extern G__linked_taginfo G__libLHCfFunctionLN_SimpleList;
extern G__linked_taginfo G__libLHCfFunctionLN_StructFiberPos;
extern G__linked_taginfo G__libLHCfFunctionLN_ConScifiPosition;
extern G__linked_taginfo G__libLHCfFunctionLN_TH2F;
extern G__linked_taginfo G__libLHCfFunctionLN_ConShowerLeakage;
extern G__linked_taginfo G__libLHCfFunctionLN_LHCfRunInfo;
extern G__linked_taginfo G__libLHCfFunctionLN_LHCfRunInfocLcLDEF_BEAMTAG;
extern G__linked_taginfo G__libLHCfFunctionLN_LHCfRunInfoTable;
extern G__linked_taginfo G__libLHCfFunctionLN_vectorlELHCfRunInfomUcOallocatorlELHCfRunInfomUgRsPgR;
extern G__linked_taginfo G__libLHCfFunctionLN_reverse_iteratorlEvectorlELHCfRunInfomUcOallocatorlELHCfRunInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfFunctionLN_PMTSatu;
extern G__linked_taginfo G__libLHCfFunctionLN_PMTSatucLcLPMTTable;
extern G__linked_taginfo G__libLHCfFunctionLN_PMTSatuCorrection;
extern G__linked_taginfo G__libLHCfFunctionLN_ParticleID01;
extern G__linked_taginfo G__libLHCfFunctionLN_ParticleID02;
extern G__linked_taginfo G__libLHCfFunctionLN_A1Phys;
extern G__linked_taginfo G__libLHCfFunctionLN_SciFiPosCalculation;
extern G__linked_taginfo G__libLHCfFunctionLN_TGraphErrors;
extern G__linked_taginfo G__libLHCfFunctionLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__libLHCfFunctionLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__libLHCfFunctionLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfFunctionLN_ScifiIncidentPosition02;
extern G__linked_taginfo G__libLHCfFunctionLN_ScintiPosDependence;
extern G__linked_taginfo G__libLHCfFunctionLN_SPSAdamo;
extern G__linked_taginfo G__libLHCfFunctionLN_SPSAdamoPedeSubtract;
extern G__linked_taginfo G__libLHCfFunctionLN_TransitionFit;
extern G__linked_taginfo G__libLHCfFunctionLN_RHICfRunInfo;
extern G__linked_taginfo G__libLHCfFunctionLN_RHICfRunInfocLcLDEF_BEAMTAG;
extern G__linked_taginfo G__libLHCfFunctionLN_RHICfRunInfoTable;
extern G__linked_taginfo G__libLHCfFunctionLN_vectorlERHICfRunInfomUcOallocatorlERHICfRunInfomUgRsPgR;
extern G__linked_taginfo G__libLHCfFunctionLN_reverse_iteratorlEvectorlERHICfRunInfomUcOallocatorlERHICfRunInfomUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
