/********************************************************************
* libLHCfEvent.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libLHCfEvent.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibLHCfEvent();
extern void G__cpp_setup_inheritancelibLHCfEvent();
extern void G__cpp_setup_typetablelibLHCfEvent();
extern void G__cpp_setup_memvarlibLHCfEvent();
extern void G__cpp_setup_globallibLHCfEvent();
extern void G__cpp_setup_memfunclibLHCfEvent();
extern void G__cpp_setup_funclibLHCfEvent();
extern void G__set_cpp_environmentlibLHCfEvent();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LHCfEvent.h"
#include "LHCfDef.h"
#include "A1Raw.h"
#include "A1Cal1.h"
#include "A1Cal2.h"
#include "A1Cal2M.h"
#include "A1Phys.h"
#include "A1Info.h"
#include "A1Scl.h"
#include "A1Rec1.h"
#include "A1Rec2.h"
#include "A2Raw.h"
#include "A2Cal1.h"
#include "A2Cal2.h"
#include "A2Cal2M.h"
#include "A2Phys.h"
#include "A2Rec1.h"
#include "A2Rec2.h"
#include "A2Rec3.h"
#include "A2Info.h"
#include "A2Scl.h"
#include "A2Raw_pPb2013.h"
#include "A1Raw_pp2015.h"
#include "A2Raw_pp2015.h"
#include "A1Scl_pp2015.h"
#include "A2Scl_pp2015.h"
#include "A2Raw_pPb2016.h"
#include "RHICfRaw_Op2017.h"
#include "RHICfScl_Op2017.h"
#include "RawL1T.h"
#include "SclL1T.h"
#include "Rec0.h"
#include "A1Cal1AccumHist.h"
#include "A2Cal1AccumHist.h"
#include "A1Cal2AccumHist.h"
#include "A2Cal2AccumHist.h"
#include "A1PhysAccumHist.h"
#include "A2PhysAccumHist.h"
#include "A1CountArray.h"
#include "A2CountArray.h"
#include "A1CalEventHist.h"
#include "A2CalEventHist.h"
#include "SimP.h"
#include "SimIncidents.h"
#include "GParam.h"
#include "GParamD64.h"
#include "SPSAdamo.h"
#include "SPSAdamoRec0.h"
#include "SPSAdamoHist.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libLHCfEventLN_TClass;
extern G__linked_taginfo G__libLHCfEventLN_TBuffer;
extern G__linked_taginfo G__libLHCfEventLN_TMemberInspector;
extern G__linked_taginfo G__libLHCfEventLN_TObject;
extern G__linked_taginfo G__libLHCfEventLN_TNamed;
extern G__linked_taginfo G__libLHCfEventLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__libLHCfEventLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__libLHCfEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libLHCfEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfEventLN_TObjArray;
extern G__linked_taginfo G__libLHCfEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libLHCfEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__libLHCfEventLN_A1Raw;
extern G__linked_taginfo G__libLHCfEventLN_A1RawcLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal1;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal1cLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal1cLcLGPIOFLAG0;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal1cLcLGPIOFLAG2;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal2;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal2cLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal2cLcLGPIOFLAG0;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal2cLcLGPIOFLAG2;
extern G__linked_taginfo G__libLHCfEventLN_A1Phys;
extern G__linked_taginfo G__libLHCfEventLN_A1Info;
extern G__linked_taginfo G__libLHCfEventLN_A1Scl;
extern G__linked_taginfo G__libLHCfEventLN_A2Raw;
extern G__linked_taginfo G__libLHCfEventLN_A2RawcLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal2;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal1;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal1cLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal1cLcLGPIOFLAG0;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal1cLcLGPIOFLAG2;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal1cLcLBUNCHCONFFLAG;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal2cLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal2cLcLGPIOFLAG0;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal2cLcLGPIOFLAG2;
extern G__linked_taginfo G__libLHCfEventLN_A2Phys;
extern G__linked_taginfo G__libLHCfEventLN_Rec0;
extern G__linked_taginfo G__libLHCfEventLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__libLHCfEventLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfEventLN_Rec0cLcLDEF_EVQUALITY;
extern G__linked_taginfo G__libLHCfEventLN_Rec0cLcLDEF_BEAMTAG;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal2M;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal2McLcLBUNCHCONFFLAG;
extern G__linked_taginfo G__libLHCfEventLN_A2Info;
extern G__linked_taginfo G__libLHCfEventLN_A2Scl;
extern G__linked_taginfo G__libLHCfEventLN_RawL1T;
extern G__linked_taginfo G__libLHCfEventLN_SclL1T;
extern G__linked_taginfo G__libLHCfEventLN_GParam;
extern G__linked_taginfo G__libLHCfEventLN_GParamD64;
extern G__linked_taginfo G__libLHCfEventLN_SPSAdamo;
extern G__linked_taginfo G__libLHCfEventLN_A1Raw_pp2015;
extern G__linked_taginfo G__libLHCfEventLN_A1Raw_pp2015cLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_A2Raw_pp2015;
extern G__linked_taginfo G__libLHCfEventLN_A2Raw_pp2015cLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_A1Scl_pp2015;
extern G__linked_taginfo G__libLHCfEventLN_A2Scl_pp2015;
extern G__linked_taginfo G__libLHCfEventLN_A2Raw_pPb2013;
extern G__linked_taginfo G__libLHCfEventLN_A2Raw_pPb2013cLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_A2Raw_pPb2016;
extern G__linked_taginfo G__libLHCfEventLN_A2Raw_pPb2016cLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_RHICfRaw_Op2017;
extern G__linked_taginfo G__libLHCfEventLN_RHICfRaw_Op2017cLcLbank;
extern G__linked_taginfo G__libLHCfEventLN_LHCfEvent;
extern G__linked_taginfo G__libLHCfEventLN_LHCfDef;
extern G__linked_taginfo G__libLHCfEventLN_LHCfDefcLcLDef_TOWER;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal2M;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal2McLcLBUNCHCONFFLAG;
extern G__linked_taginfo G__libLHCfEventLN_A1Rec1;
extern G__linked_taginfo G__libLHCfEventLN_A1Rec2;
extern G__linked_taginfo G__libLHCfEventLN_A1Rec2cLcLBITMAP_FLAGANALYSIS;
extern G__linked_taginfo G__libLHCfEventLN_A2Rec1;
extern G__linked_taginfo G__libLHCfEventLN_A2Rec2;
extern G__linked_taginfo G__libLHCfEventLN_A2Rec3;
extern G__linked_taginfo G__libLHCfEventLN_RHICfScl_Op2017;
extern G__linked_taginfo G__libLHCfEventLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__libLHCfEventLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__libLHCfEventLN_TH1;
extern G__linked_taginfo G__libLHCfEventLN_TH1F;
extern G__linked_taginfo G__libLHCfEventLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__libLHCfEventLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__libLHCfEventLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfEventLN_TCanvas;
extern G__linked_taginfo G__libLHCfEventLN_TPad;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal1AccumHist;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal1AccumHistcLcLDATA_VERSION;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal1AccumHist;
extern G__linked_taginfo G__libLHCfEventLN_A1Cal2AccumHist;
extern G__linked_taginfo G__libLHCfEventLN_A2Cal2AccumHist;
extern G__linked_taginfo G__libLHCfEventLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__libLHCfEventLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__libLHCfEventLN_TH2F;
extern G__linked_taginfo G__libLHCfEventLN_A1PhysAccumHist;
extern G__linked_taginfo G__libLHCfEventLN_A2PhysAccumHist;
extern G__linked_taginfo G__libLHCfEventLN_TGraph;
extern G__linked_taginfo G__libLHCfEventLN_A1CountArray;
extern G__linked_taginfo G__libLHCfEventLN_A2CountArray;
extern G__linked_taginfo G__libLHCfEventLN_TText;
extern G__linked_taginfo G__libLHCfEventLN_A1CalEventHist;
extern G__linked_taginfo G__libLHCfEventLN_A1CalEventHistcLcLGPIOLOGIC;
extern G__linked_taginfo G__libLHCfEventLN_A1CalEventHistcLcLDISPLAY_VERSION;
extern G__linked_taginfo G__libLHCfEventLN_A2CalEventHist;
extern G__linked_taginfo G__libLHCfEventLN_A2CalEventHistcLcLGPIOLOGIC;
extern G__linked_taginfo G__libLHCfEventLN_A2CalEventHistcLcLDISPLAY_VERSION;
extern G__linked_taginfo G__libLHCfEventLN_SimP;
extern G__linked_taginfo G__libLHCfEventLN_SimIncidents;
extern G__linked_taginfo G__libLHCfEventLN_SPSAdamoRec0;
extern G__linked_taginfo G__libLHCfEventLN_SPSAdamoHist;

/* STUB derived class for protected member access */
