/********************************************************************
* libEventView.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libEventView.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibEventView();
extern void G__cpp_setup_inheritancelibEventView();
extern void G__cpp_setup_typetablelibEventView();
extern void G__cpp_setup_memvarlibEventView();
extern void G__cpp_setup_globallibEventView();
extern void G__cpp_setup_memfunclibEventView();
extern void G__cpp_setup_funclibEventView();
extern void G__set_cpp_environmentlibEventView();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FrameEventView.h"
#include "TGTextButtonMod.h"
#include "EventMarker.h"
#include "EventTagFrame.h"
#include "MkPedestalFrame.h"
#include "GainConfigWindow.h"
#include "AdamoFrame.h"
#include "MkAdamoPedestalFrame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libEventViewLN_TClass;
extern G__linked_taginfo G__libEventViewLN_TBuffer;
extern G__linked_taginfo G__libEventViewLN_TMemberInspector;
extern G__linked_taginfo G__libEventViewLN_TObject;
extern G__linked_taginfo G__libEventViewLN_string;
extern G__linked_taginfo G__libEventViewLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libEventViewLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libEventViewLN_TList;
extern G__linked_taginfo G__libEventViewLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libEventViewLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libEventViewLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__libEventViewLN_TFile;
extern G__linked_taginfo G__libEventViewLN_TCanvas;
extern G__linked_taginfo G__libEventViewLN_TQObject;
extern G__linked_taginfo G__libEventViewLN_TQObjSender;
extern G__linked_taginfo G__libEventViewLN_TGObject;
extern G__linked_taginfo G__libEventViewLN_TGWindow;
extern G__linked_taginfo G__libEventViewLN_TAttMarker;
extern G__linked_taginfo G__libEventViewLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__libEventViewLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__libEventViewLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libEventViewLN_TGFrame;
extern G__linked_taginfo G__libEventViewLN_TGCompositeFrame;
extern G__linked_taginfo G__libEventViewLN_TGTextButton;
extern G__linked_taginfo G__libEventViewLN_TGMainFrame;
extern G__linked_taginfo G__libEventViewLN_TGTransientFrame;
extern G__linked_taginfo G__libEventViewLN_TGWidget;
extern G__linked_taginfo G__libEventViewLN_TGPopupMenu;
extern G__linked_taginfo G__libEventViewLN_TGButton;
extern G__linked_taginfo G__libEventViewLN_TGPictureButton;
extern G__linked_taginfo G__libEventViewLN_TGCheckButton;
extern G__linked_taginfo G__libEventViewLN_TGRadioButton;
extern G__linked_taginfo G__libEventViewLN_TGTab;
extern G__linked_taginfo G__libEventViewLN_TH1F;
extern G__linked_taginfo G__libEventViewLN_TAttBBox2D;
extern G__linked_taginfo G__libEventViewLN_TTree;
extern G__linked_taginfo G__libEventViewLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__libEventViewLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__libEventViewLN_TGTextEntry;
extern G__linked_taginfo G__libEventViewLN_TGTextButtonMod;
extern G__linked_taginfo G__libEventViewLN_A1Cal1;
extern G__linked_taginfo G__libEventViewLN_A1Cal2;
extern G__linked_taginfo G__libEventViewLN_A2Cal2;
extern G__linked_taginfo G__libEventViewLN_A2Cal1;
extern G__linked_taginfo G__libEventViewLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__libEventViewLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libEventViewLN_SPSAdamo;
extern G__linked_taginfo G__libEventViewLN_LHCfEvent;
extern G__linked_taginfo G__libEventViewLN_A1RawToCal1;
extern G__linked_taginfo G__libEventViewLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__libEventViewLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_A1CalEventHist;
extern G__linked_taginfo G__libEventViewLN_A1PedeSubtract;
extern G__linked_taginfo G__libEventViewLN_A2RawToCal1;
extern G__linked_taginfo G__libEventViewLN_A2RawToCal1Silicon;
extern G__linked_taginfo G__libEventViewLN_A2CalEventHist;
extern G__linked_taginfo G__libEventViewLN_A2PedeSubtract;
extern G__linked_taginfo G__libEventViewLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__libEventViewLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__libEventViewLN_A1LHCCrossTalk;
extern G__linked_taginfo G__libEventViewLN_A1Cal1ToCal2;
extern G__linked_taginfo G__libEventViewLN_A2Cal1ToCal2;
extern G__linked_taginfo G__libEventViewLN_A1GainCalibration;
extern G__linked_taginfo G__libEventViewLN_A2GainCalibration;
extern G__linked_taginfo G__libEventViewLN_RawL1TDraw;
extern G__linked_taginfo G__libEventViewLN_FrameEventView;
extern G__linked_taginfo G__libEventViewLN_FrameEventViewcLcLHandleMenuID;
extern G__linked_taginfo G__libEventViewLN_TMarker;
extern G__linked_taginfo G__libEventViewLN_EventMarker;
extern G__linked_taginfo G__libEventViewLN_TGLabel;
extern G__linked_taginfo G__libEventViewLN_TGStatusBar;
extern G__linked_taginfo G__libEventViewLN_EventTagFrame;
extern G__linked_taginfo G__libEventViewLN_EventTagFramecLcLEventTagWedgetID;
extern G__linked_taginfo G__libEventViewLN_TGNumberEntry;
extern G__linked_taginfo G__libEventViewLN_TGHProgressBar;
extern G__linked_taginfo G__libEventViewLN_MkPedestalFrame;
extern G__linked_taginfo G__libEventViewLN_GainConfigWindow;
extern G__linked_taginfo G__libEventViewLN_SPSAdamoHist;
extern G__linked_taginfo G__libEventViewLN_SPSAdamoPedeSubtract;
extern G__linked_taginfo G__libEventViewLN_AdamoFrame;
extern G__linked_taginfo G__libEventViewLN_MkAdamoPedestalFrame;

/* STUB derived class for protected member access */
