/********************************************************************
* libLHCfSC.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libLHCfSC.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibLHCfSC();
extern void G__cpp_setup_inheritancelibLHCfSC();
extern void G__cpp_setup_typetablelibLHCfSC();
extern void G__cpp_setup_memvarlibLHCfSC();
extern void G__cpp_setup_globallibLHCfSC();
extern void G__cpp_setup_memfunclibLHCfSC();
extern void G__cpp_setup_funclibLHCfSC();
extern void G__set_cpp_environmentlibLHCfSC();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TLHCFSDATA.h"
#include "TLHCFDIPDATAH.h"
#include "TLHCFDIPDATAL.h"
#include "TLHCFDIPDATAVH.h"
#include "SocketControl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libLHCfSCLN_TClass;
extern G__linked_taginfo G__libLHCfSCLN_TBuffer;
extern G__linked_taginfo G__libLHCfSCLN_TMemberInspector;
extern G__linked_taginfo G__libLHCfSCLN_TObject;
extern G__linked_taginfo G__libLHCfSCLN_TNamed;
extern G__linked_taginfo G__libLHCfSCLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libLHCfSCLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfSCLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libLHCfSCLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libLHCfSCLN_LHCFSDATA_HEADER;
extern G__linked_taginfo G__libLHCfSCLN_CPWS_CH;
extern G__linked_taginfo G__libLHCfSCLN_CPWS1_DATA;
extern G__linked_taginfo G__libLHCfSCLN_CPWS2_DATA;
extern G__linked_taginfo G__libLHCfSCLN_AGILENT_CH;
extern G__linked_taginfo G__libLHCfSCLN_AGILENT_MOD;
extern G__linked_taginfo G__libLHCfSCLN_AGILENT_DATA;
extern G__linked_taginfo G__libLHCfSCLN_TRHX_DATA;
extern G__linked_taginfo G__libLHCfSCLN_ENCODER_DATA;
extern G__linked_taginfo G__libLHCfSCLN_ADC_DATA;
extern G__linked_taginfo G__libLHCfSCLN_LHCFSDATA;
extern G__linked_taginfo G__libLHCfSCLN_TLHCFSDATA;
extern G__linked_taginfo G__libLHCfSCLN_DIP_LHCF_Arm;
extern G__linked_taginfo G__libLHCfSCLN_DIP_LHCF_COINCIDENCE;
extern G__linked_taginfo G__libLHCfSCLN_DIP_LHCF_EXPTSTATUS;
extern G__linked_taginfo G__libLHCfSCLN_DIP_LHCF_INTERLOCK;
extern G__linked_taginfo G__libLHCfSCLN_DIP_LHCF_LUMINOSITY;
extern G__linked_taginfo G__libLHCfSCLN_DIP_LHCF_HS_LHC_INJECTION;
extern G__linked_taginfo G__libLHCfSCLN_DIP_LHCF_HS_LHC_ADJUST;
extern G__linked_taginfo G__libLHCfSCLN_DIP_LHCF_HS_LHC_BEAMDUMP;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_BPM;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_BPM_M;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_ENERGY;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_INTENSITY;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_INTENSITYPERBUNCH;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_INTENSITYPERBUNCH_S;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_LUMINOSITYAVERAGE;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_LUMINOSITYPERBUNCH;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_LUMINOSITYSCAN;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_SIZE;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_SIZE_AVERAGE;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_WIRESCANNER;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_BEAM_BETASTAR;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_HS_LHC_INJECTION;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_HS_LHC_ADJUST;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_HS_LHC_BEAMDUMP;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_RUNCONTROL_BEAMMODE;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_RUNCONTROL_BUNCHCONFIG;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_RUNCONTROL_FILLNUMBER;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_RUNCONTROL_FILLSCHEMA;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_RUNCONTROL_MACHINEMODE;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_RUNCONTROL_PAGE;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_RUNCONTROL_SAFEBEAM;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_RUNCONTROL_RUNCONFIGURATION;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_TIMING_POSTMORTEM;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_TIMING_RXCLOCKS;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_TIMING_RXFREV;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ACC_MACHINE_COLLPOSITION;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ATLAS_CLOCK_SELECTION;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ATLAS_FILLLUMI;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ATLAS_LUMIPERBUNCH;
extern G__linked_taginfo G__libLHCfSCLN_DIP_ATLAS_LUMINOSITY;
extern G__linked_taginfo G__libLHCfSCLN_DIP_LHCF_DOSIMETER;
extern G__linked_taginfo G__libLHCfSCLN_LHCFDIPDATAH;
extern G__linked_taginfo G__libLHCfSCLN_LHCFDIPDATAL;
extern G__linked_taginfo G__libLHCfSCLN_LHCFDIPDATAVH;
extern G__linked_taginfo G__libLHCfSCLN_TLHCFDIPDATAH;
extern G__linked_taginfo G__libLHCfSCLN_TLHCFDIPDATAL;
extern G__linked_taginfo G__libLHCfSCLN_TLHCFDIPDATAVH;
extern G__linked_taginfo G__libLHCfSCLN_SocketControl;

/* STUB derived class for protected member access */
